import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Videos | Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className={`antialiased bg-white`}>
      <div>{children}</div>
    </section>
  );
}
